import 'package:btl_flutter/Login/Component/Button/BtnLogin.dart';
import 'package:btl_flutter/Login/Component/Button/FogotPassWord.dart';
import 'package:btl_flutter/Login/Component/InputText/InputText1.dart';
import 'package:btl_flutter/Login/Component/InputText/InputPassword.dart';
import 'package:btl_flutter/Login/Component/Logo/Logo.dart';
import 'package:btl_flutter/Login/Component/ViewText/TextLogin.dart';
import 'package:flutter/material.dart';

import '../Component/Button/Register.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MainScreen extends StatelessWidget {
  const MainScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Container(
            width: double.infinity,
            height: double.infinity,
            clipBehavior: Clip.antiAlias,
            decoration: const BoxDecoration(color: Colors.white),
            child: Stack(children: [
              const Positioned(
                left: 93,
                top: 91,
                child: Logo(),
              ),
              Positioned(
                left: -104,
                top: -89,
                child: SizedBox(
                  width: 290,
                  height: 270,
                  // hinh tron do
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 70,
                        child: Container(
                          width: 200,
                          height: 200,
                          decoration: const ShapeDecoration(
                            color: Color(0x7CF31132),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 90,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 200,
                          decoration: const ShapeDecoration(
                            color: Color(0x7CF31132),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
               Positioned(
                left: MediaQuery.of(context).size.width / 2.7,
                top: 179.61,
                child: const TextLogin(),
              ),
              Positioned(
                left: MediaQuery.of(context).size.width / 10,
                top: 278.71,
                child: Material(
                  child: InputText1(),
                ),
              ),
              Positioned(
                left: MediaQuery.of(context).size.width / 10,
                top: 331.71,
                child: Material(
                  child: InputPassword(),
                ),
              ),
              Positioned(
                left: MediaQuery.of(context).size.width / 3.5,
                top: 411,
                child: const BtnLogin(),
              ),
              const Positioned(
                left: 20,
                  top: 511,
                  child:
                  ForgotPassWord(),
              ),
              const Positioned(
                right: 20,
                  top: 511,
                  child:
                  Register(),
              )
            ])));
  }
}
